import { Geist, Geist_Mono } from "next/font/google";
import Provider from "./provider";
import "./globals.css";
import Header from "@/components/ui/custom/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body>
        <Header/>
        <Provider>
        {children}
        </Provider>
        
      </body>
    </html>
  );
}
